### PR TITLE
specify user

### PR DESCRIPTION
**Pull request by gcmalloc**
This is a try to specifing the user for the download and the extraction of the archive.

### CODE REVIEW

**Comment by mcanevet** [comment]
@gcmalloc could you please rebase so that I can merge this?

**Comment by gcmalloc** [comment]
In the current state, the changes apported to this pull request would require to change manually the `src_target`, as any user doesn't have the right to write in it. 

I can create one subdirectory per user in the download directory and give it to the user, or if you have a better solution to propose.

I could also leave it that way and specify the behavior in the doc.

**Comment by mcanevet** [comment]
@gcmalloc I think you can just specify the behavior in the doc.

**Comment by mcanevet** [comment]
@gcmalloc you commited a merge conflict without resolving it...

**Comment by tails-developers** [comment]
I've just tried to merge it into master and got no merge conflict, so I'm not sure why it happened on your side. We're still in need of this feature.

**Comment by mcanevet** [comment]
@gcmalloc @tails-developers lint test still fails.

**Comment by tails-developers** [comment]
It seems a fix have been proposed in a pull request on gcmalloc:set_user branch : https://github.com/gcmalloc/puppet-archive/pull/1

**Comment by tails-developers** [comment]
Cool, seems the tests are green now!

**Comment by mcanevet** [comment]
@tails-developers @gcmalloc thanks

**Pull request merged**
